# Generated by Django 5.0.6 on 2024-06-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer_tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='data_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='goals_team_one',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='goals_team_two',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='goals_against',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='goals_favor',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='lost_matches',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='matches_won',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='points',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='tied_matches',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
