# Generated by Django 5.0.6 on 2024-06-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccer_tournament', '0002_alter_matches_data_start_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='team',
            name='points',
        ),
        migrations.RemoveField(
            model_name='team',
            name='position',
        ),
    ]
